// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbsncefworotytncjatu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJic25jZWZ3b3JvdHl0bmNqYXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTAyNzcsImV4cCI6MjA2MDQ2NjI3N30.d9hLjD2mTaRrlAHP13UAoPtCz9Ho5DtuZkaSBDIXmwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);